spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ${EMAIL_LOGIN}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    test-connection: false
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  thymeleaf:
    servlet:
      produce-partial-output-while-processing: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
server:
  tomcat:
    max-swallow-size: -1
  servlet:
    session:
      timeout: 30m
temporary-token:
  length: 64
  life-time: 30
remember-me:
  token: ${REMEMBER_ME_TOKEN}