spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gamezone
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:/opt/gamezonefiles/uploads

app:
  storage:
    location: file:/opt/gamezonefiles/uploads