spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: ${H2_LOGIN}
    password: ${H2_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  liquibase:
    change-log: classpath:db/changelog/master.xml
    contexts: dev
    drop-first: true
  jpa:
    hibernate:
      ddl-auto: validate
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  sql:
    init:
      mode: always
app:
  storage:
    location: uploads
logging:
  level:
    org:
      springframework:
        security: debug
      thymeleaf: error