spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    change-log: classpath:db/changelog/master.xml
    contexts: dev
  jpa:
    hibernate:
      ddl-auto: validate
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
  servlet:
    multipart:
      max-file-size: 5
      max-request-size: 5
app:
  storage:
    location: uploads
