spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    change-log: classpath:db/changelog/master.xml
    contexts: dev
    drop-first: true
  jpa:
    hibernate:
      ddl-auto: validate
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  sql:
    init:
      mode: always
app:
  storage:
    location: uploads

logging:
  level:
    org:
      springframework:
        security: debug