spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: gamezonepomoc@gmail.com
    password: peiu asyu wgia lkjx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    test-connection: false
