spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    change-log: classpath:db/changelog/master.xml
    contexts: dev
  jpa:
    hibernate:
      ddl-auto: validate
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
  servlet:
    multipart:
      max-file-size: 5
      max-request-size: 5
app:
  storage:
    location: uploads
server:
  tomcat:
    max-swallow-size: 5
  servlet:
    session:
      timeout: 30
temporary-token:
  length: 64
  life-time: 30
remember-me:
  token: 3452180c-a4b0-436f-9d29-ee067b97ddc5
logging:
  level:
    org:
      springframework:
        security: debug