spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    change-log: classpath:db/changelog/master.xml
    contexts: dev
  jpa:
    hibernate:
      ddl-auto: validate
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
app:
  storage:
    location: uploads
server:
  tomcat:
    max-swallow-size: -1
  servlet:
    session:
      timeout: 30
temporary-token:
  length: 64
  life-time: 15
remember-me:
  token: b4907550-4818-423f-a240-9dd408a521b6